### ISSUE TITLE
`predictors` undefined in the code for Bayesian Linear Regression with Uniform Prior.

### ISSUE THREAD

**Issue by codetalker7** [xKDR/CRRao.jl#11] opened 2022-06-20 09:56 UTC
In the code for Bayesian Linear Regression with a Uniform prior (in `src/bayesian/linear_regression.jl`, lines 258-280), an undefined variable `predictors` is being used. 

```julia
β ~ filldist(Uniform(-v, v), predictors)
```

For example, the following code will throw an error, complaining that `predictors` is undefined. 
```julia
using CRRao, RDatasets
mtcars = dataset("datasets", "mtcars")
container = @fitmodel(MPG ~ HP + WT + Gear, mtcars, LinearRegression(), Prior_Uniform())
```

Looking at the other models, it seems like `predictors` should be replaced by `p` (the number of columns in the dataframe), since `filldist` expects it's second argument to be an integer.

**Comment by sourish-cmi** [comment] 2022-08-23 09:37
We have fixed it as `β ~ filldist(Uniform(-v, v), p)` where `p` is the number of predictors in the models. As the issue is now solved, I am closing this issue

**Closed by sourish-cmi** 2022-08-23 09:37 UTC
